### ISSUE TITLE
Request: Tag

### ISSUE THREAD

**Issue by Kutalmis-Bercin** [Weishuo93/NN_Pred#1]
Hello @Weishuo93 

Could you please add a tag for v2406 so that OpenFOAM submodules can have a non-moving target SHA?

Many thanks.

**Comment by Weishuo93** [comment]
> Hello @Weishuo93
> 
> Could you please add a tag for v2406 so that OpenFOAM submodules can have a non-moving target SHA?
> 
> Many thanks.

Hi @Kutalmis-Bercin 

I have tested for the [develop branch of OpenFOAM](https://develop.openfoam.com/Development/openfoam/-/tree/develop?ref_type=heads), which seems to be the unreleased v2406. The latest submission of NNPred worked fine.

I have created two tags. Please check out "OF-v2312" and "OF-v2406" for OF submodules.

**Comment by Weishuo93** [comment]
@Kutalmis-Bercin I closed this issue since the tags have been created. Don't hesitate to hit me when anything is needed.
